/* Generated by Yosys 0.29+0 (git sha1 f790e0047, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module ring_counter(Clock, Reset, Count_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input Clock;
  wire Clock;
  output [3:0] Count_out;
  wire [3:0] Count_out;
  wire [3:0] Count_temp;
  input Reset;
  wire Reset;
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(_00_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(_00_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_00_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(_00_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__dfstp_2 _13_ (
    .CLK(Clock),
    .D(Count_temp[3]),
    .Q(Count_temp[0]),
    .SET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(Clock),
    .D(Count_temp[0]),
    .Q(Count_temp[1]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(Clock),
    .D(Count_temp[1]),
    .Q(Count_temp[2]),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(Clock),
    .D(Count_temp[2]),
    .Q(Count_temp[3]),
    .RESET_B(_08_)
  );
  assign Count_out = Count_temp;
  assign _00_ = Reset;
  assign _05_ = _01_;
  assign _06_ = _02_;
  assign _07_ = _03_;
  assign _08_ = _04_;
endmodule
